lines = [
'"use strict";',
'',
'const activeWatches = new Map();',
'const mediaTypeCache = new Map();',
'const WATCH_MAX_AGE_MS = 12 * 60 * 1000;',
'',
'function mediaDownloadUrl(mediaId) {',
'  return `https://labs.google/fx/api/trpc/media.getMediaUrlRedirect?name=${encodeURIComponent(mediaId)}`;',
'}',
'',
'function typeFromMediaResponse(response) {',
'  const contentType = response.headers.get("content-type") || "";',
'  const finalUrl = response.url || "";',
'  if (/video/i.test(contentType) || /\\/video\\//i.test(finalUrl)) return "video";',
'  if (/image/i.test(contentType) || /\\/image\\//i.test(finalUrl)) return "image";',
'  return "unknown";',
'}',
'',
'async function classifyMediaId(mediaId) {',
'  if (mediaTypeCache.has(mediaId)) return mediaTypeCache.get(mediaId);',
'',
'  let response;',
'  try {',
'    response = await fetch(mediaDownloadUrl(mediaId), {',
'      method: "GET",',
'      credentials: "include",',
'      cache: "no-store",',
'      headers: { Range: "bytes=0-0" },',
'    });',
'    const type = response.ok ? typeFromMediaResponse(response) : "unknown";',
'    await response.body?.cancel().catch(() => undefined);',
'    mediaTypeCache.set(mediaId, type);',
'    return type;',
'  } catch {',
'    await response?.body?.cancel().catch(() => undefined);',
'    mediaTypeCache.set(mediaId, "unknown");',
'    return "unknown";',
'  }',
'}',
'',
'async function classifyMediaIds(mediaIds) {',
'  const types = {};',
'  let cursor = 0;',
'  const workers = Array.from({ length: Math.min(6, mediaIds.length) }, async () => {',
'    while (cursor < mediaIds.length) {',
'      const index = cursor;',
'      cursor += 1;',
'      const mediaId = mediaIds[index];',
'      types[mediaId] = await classifyMediaId(mediaId);',
'    }',
'  });',
'  await Promise.all(workers);',
'  return types;',
'}',
'',
'function looksLikeVideoDownload(item) {',
'  const combined = [item.url, item.finalUrl, item.filename, item.mime, item.referrer]',
'    .filter(Boolean)',
'    .join(" ");',
'  return /(?:video\\/|\\.mp4(?:\\?|$)|\\.webm(?:\\?|$)|\\.mov(?:\\?|$)|flow-content\\.google|googlevideo\\.com)/i',
'    .test(combined);',
'}',
'',
'function expireOldWatches() {',
'  const now = Date.now();',
'  for (const [tabId, watch] of activeWatches) {',
'    if (now - watch.startedAt > WATCH_MAX_AGE_MS) activeWatches.delete(tabId);',
'  }',
'}',
'',
'chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {',
'  if (message?.type === "FLOW_WATCH_DOWNLOAD") {',
'    const tabId = sender.tab?.id;',
'    if (typeof tabId !== "number") {',
'      sendResponse({ ok: false, error: "The Flow tab could not be identified." });',
'      return false;',
'    }',
'    activeWatches.set(tabId, { token: message.token, startedAt: Date.now() });',
'    sendResponse({ ok: true });',
'    return false;',
'  }',
'',
'  if (message?.type === "FLOW_CANCEL_DOWNLOAD_WATCH") {',
'    const tabId = sender.tab?.id;',
'    if (typeof tabId === "number") {',
'      const watch = activeWatches.get(tabId);',
'      if (!message.token || watch?.token === message.token) activeWatches.delete(tabId);',
'    }',
'    sendResponse({ ok: true });',
'    return false;',
'  }',
'',
'  if (message?.type === "FLOW_DIRECT_DOWNLOAD") {',
'    const options = {',
'      url: message.url,',
'      filename: message.filename,',
'      conflictAction: "uniquify",',
'      saveAs: false,',
'    };',
'    chrome.downloads.download(options)',
'      .then((downloadId) => sendResponse({ ok: true, downloadId }))',
'      .catch((error) => sendResponse({ ok: false, error: error.message }));',
'    return true;',
'  }',
'',
'  if (message?.type === "FLOW_DOWNLOAD_MEDIA") {',
'    chrome.downloads.download({',
'      url: mediaDownloadUrl(message.mediaId),',
'      filename: message.filename,',
'      conflictAction: "uniquify",',
'      saveAs: false,',
'    })',
'      .then((downloadId) => sendResponse({ ok: true, downloadId }))',
'      .catch((error) => sendResponse({ ok: false, error: error.message }));',
'    return true;',
'  }',
'',
'  if (message?.type === "FLOW_CLASSIFY_MEDIA_IDS") {',
'    const mediaIds = [...new Set(message.mediaIds || [])]',
'      .filter((value) => typeof value === "string")',
'      .slice(0, 1000);',
'    classifyMediaIds(mediaIds)',
'      .then((types) => sendResponse({ ok: true, types }))',
'      .catch((error) => sendResponse({ ok: false, error: error.message, types: {} }));',
'    return true;',
'  }',
'',
'  return false;',
'});',
'',
'chrome.downloads.onCreated.addListener((item) => {',
'  expireOldWatches();',
'  if (!activeWatches.size) return;',
'  if (activeWatches.size > 1 && !looksLikeVideoDownload(item)) return;',
'',
'  for (const [tabId, watch] of activeWatches) {',
'    activeWatches.delete(tabId);',
'    chrome.tabs.sendMessage(tabId, {',
'      type: "FLOW_DOWNLOAD_DETECTED",',
'      token: watch.token,',
'      downloadId: item.id,',
'      filename: item.filename || "",',
'    }).catch(() => undefined);',
'    break;',
'  }',
'});',
]

with open("background.js", "w") as f:
    f.write("\n".join(lines) + "\n")
